### ISSUE TITLE
Discriminant loss does not decrease

### ISSUE THREAD

**Issue by WelkinYang** [alsdudrla10/Discriminator-Guidance#5]
Thanks for your excellent contribution, I am trying to apply this work to other domains, but unfortunately I found that the loss function of the discriminator could not be reduced in the experiments and the Bce loss was always higher than 0.6. I used VPSDE and generated 10 steps results with a maximum likelihood based SDE solver to serve as fake data for the discriminator. I used the same Unet as in the repository. When i change the Unet encoder to the whole Unet, the loss become more low than the loss of Unet encoder.  Looking forward to get some advice. Thank you.

**Comment by Psw-coder** [comment]
Hello, have you solved this problem? I encountered the same issue—the BCE loss was always approximately 0.69.
